// Code generated by "stringer -type=TermType"; DO NOT EDIT.

package fmr

import "strconv"

const _TermType_name = "EOFNonterminalTerminalAnyList"

var _TermType_index = [...]uint8{0, 3, 14, 22, 25, 29}

func (i TermType) String() string {
	if i >= TermType(len(_TermType_index)-1) {
		return "TermType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TermType_name[_TermType_index[i]:_TermType_index[i+1]]
}
