// Code generated by "stringer -type itemType"; DO NOT EDIT.

package bnf

import "strconv"

const _itemType_name = "itemErroritemEOFitemIdentifieritemLeftBraceitemRightBraceitemLeftParentheseitemRightParentheseitemEqualSignitemOritemStaritemPlusitemOptitemStringitemChar"

var _itemType_index = [...]uint8{0, 9, 16, 30, 43, 57, 75, 94, 107, 113, 121, 129, 136, 146, 154}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
